config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  root "posts#index"
  # routes for users
  resources :users do
    get "/edit_password", to: "users#edit_password", as: 'edit_password'
    patch 'update_password', to: 'users#update_password', as: 'update_password'
  end
  # routes for session/sign in user
  get 'session/new', to: 'sessions#new'
  delete '/sign_out', to: 'sessions#destroy'
  resources :sessions, only: [:create]
  # routes for posts and nested routes for comments
  resources :posts do
    resources :comments, only: [:destroy, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true, uniqueness: true
    validates :body, presence: true, length: { minimum: 50 }

    has_many :comments, dependent: :destroy
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :comments, dependent: :destroy
    has_many :posts, dependent: :destroy
    # must have validation for email format ask TA
    validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :password, presence: true, length: {minimum: 3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def authenticate_user!
        if !user_signed_in?
            flash[:alert] = "Please sign in first!"
            redirect_to session_new_path
        end
    end



    def user_signed_in?
        current_user.present?
    end
    helper_method :user_signed_in?
    
    def current_user
        @current_user ||= User.find_by_id cookies[:user_id]
    end
    helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_post
    
    def create
        @comment = Comment.new params.require(:comment).permit(:body, :user_id)
        @comment.post = @post
        @comment.user_id = cookies[:user_id]
        if @comment.save
            puts "saved"
            redirect_to post_path(@post.id)
        else
            puts 'did not save'
            redirect_to post_path(@post.id)
            
        end
    end

    def destroy
        @comment = Comment.find params[:id]
        @comment.destroy
        redirect_to post_path(@post.id)
    end

    private

    def find_post
        @post = Post.find params[:post_id]
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @post = Post.all.order(id: :desc)
        render status: 202
    end

    def show
        @post = Post.find params[:id]
        @comment_username = @post.comments
        @username = User.find_by_id @post.user_id
        @comment = Comment.new
       
    end
    
    def new
        @post = Post.new
    end

    def create
        @post = Post.new params.require(:post).permit(:title, :body, :user_id)
        @post.user_id = cookies[:user_id]
        if @post.save 
            redirect_to post_path(@post.id)
        else 
            p "could not save post"
            redirect_to root_path
        end
    end

    def destroy
        @post = Post.find params[:id]
        @post.destroy
        redirect_to root_path
        
        

    end

    def edit
        @post = Post.find params[:id]
    end

    def update
        @post = Post.find params[:id]
        if @post.update params.require(:post).permit(:title, :body)
            redirect_to post_path(@post.id)
        else 
            redirect_to edit_post_path
        end
        
    end

    private

    # def post_params
    #     params.require(:post).permit(:title,:body)
    # end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.find_by(email: user_params[:email])
        p user_params
        
        if @user && @user.authenticate(user_params[:password])
            p @user
            flash[:notice] = "Logged In"
            cookies[:user_id] = @user.id
            redirect_to root_path
        else 
            p @user
            flash[:notice] = "Invalid email or password"
            redirect_to session_new_path
        end
    end

    def destroy
        cookies[:user_id] = nil
        flash.notice = "Logged out"
        redirect_to root_path
    end
    
    private

    def user_params
        params.require(:user).permit(:name, :email, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.password == @user.password_confirmation
      @user.save
      redirect_to root_path
    else
      flash[:notice] = "Password is not the same"
      redirect_to new_user_path
    end
  end

  def edit
    @user = User.find_by_id cookies[:user_id]
  end

  def update
    @user = User.find_by_id cookies[:user_id]
    if @user.update user_params
      flash[:notice] = "sucessfully updated"
      redirect_to posts_path
    end
  end

  def edit_password
    @user = User.find_by_id cookies[:user_id]
  end

  def update_password
    @user = User.find_by_id cookies[:user_id]
    if @user&.authenticate params[:user][:current_password]
      new_password = params[:user][:new_password]
      new_password_confirmation = params[:user][:new_password_confirmation]
      if new_password == new_password_confirmation
        if @user.update password: new_password, password_confirmation: new_password_confirmation
          flash[:alert] = "password updated!"
          redirect_to root_path, status: 303
        else
          flash[:alert] = "password update failed"
          render :edit_password, status: 303
        end
      else
        flash[:alert] = "Old password does not match"
        render :edit_password, status: 303
      end
      
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogOnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav>
  <% if user_signed_in? %>
  <h2 class = "nav-item" ><%= link_to "Blog On Rails", posts_path %></h3>
  <h3 class = "nav-item1" > <%= link_to "New Post", new_post_path %> </h3>
  <h3 class = "nav-item2" > <%= link_to "Home", posts_path %> </h3>
  <% else %>
  <h2 class = "nav-item" ><%= link_to "Blog On Rails", posts_path %></h3>
  <h3 class = "nav-item1" > <%= link_to "New Post", session_new_path %> </h3>
  <h3 class = "nav-item2" > <%= link_to "Home", posts_path %> </h3>
  <% end %>
  
  </nav>
  <%if(user_signed_in?) %>
       <h2>Signed in as <%= link_to "#{current_user.name}" , edit_user_path(current_user.id) %></h2> 
      <%= button_to "Log out", sign_out_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign In Page', session_new_path%>
      <%= link_to 'Sign Up Page', new_user_path%>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= form_with model:@post do |form| %>
    <div>
    <%= form.label :title, "Title", class: 'edit-title'  %>
    <br>
    <%= form.text_field :title, class: "input-field" %>
    <br>
    <%= form.label :body, "Caption", class: "edit-caption" %>
    <br>
    <%= form.text_field :body, class: "input-field" %>
    <br>
    <%= form.submit "Update Post", class: 'btn btn-outline-primary update-button' %>
    </div>
<%end%>

app/views/posts/index.html.erb
<div class = "grid-container" >
<% @post.each do |post| %>
    <div class = "container" >
    <h3 class = "title" > <%= link_to post.title, post_path(post.id) %> </h3>
    <p class = "preview" > <%= post.body %> </p>
    </div>
<% end %>
</div>

app/views/posts/new.html.erb
<%= form_with model:@post do |form| %>
    <div>
    <%= form.label :title, "Title", class: "edit-title"%>
    <br>
    <%= form.text_field :title, class: "input-field" %>
    <br>
    <%= form.label :body, "Caption", class: "edit-caption" %>
    <br>
    <%= form.text_field :body, class: "input-field" %>
    <br>
    <%= form.submit "Create", class: "btn btn-outline-primary update-button"%>
    </div>
<%end%>

app/views/posts/show.html.erb
<div class = "post" >
<h3 class = "show-title"> <%= @post.title %> </h3>
<p class = "show-body" > <%= @post.body %> </p>
<p class = "created-at"> Posted <%= time_ago_in_words(@post.created_at) %> ago</p>
<p class = "created-at"> Created By <%= @username.name %> </p>
<% if user_signed_in? && current_user.id == @post.user_id %>
<button type="button" class="btn btn-outline-primary"><%= link_to "Edit", edit_post_path(@post.id) %></button>
<%= button_to("Delete", post_path, method: :delete, class: 'btn btn-outline-primary delete-button')%>   
<% end %>
</div>


<div class = "comment-form" >
<%= form_with(model:[@post, @comment]) do |form| %>
    <h3 class = "form-body">
    <%= form.label :body, "Comment"%>
    </h3>
    <div class = "text-area">
    <%= form.text_field :body, placeholder: "What's on your mind?"%>
    </div>
    <% if user_signed_in? %>
    <%= form.submit("Submit",class: 'btn btn-outline-primary')  %>
    <% end %>
    
<%end%>
</div>
<div class = "comments"  >
<%  if @post.comments %>
    <% @post.comments.each do |comment| %>
      <p class = "comment"> <%= comment.body %> </p>
      <p class = "created-at"> Created <%= time_ago_in_words(comment.created_at) %> ago</p>
      <p class = "created-at"> Created By <%= (User.find_by_id comment.user_id).name %></p>
      <% if user_signed_in? && current_user.id == comment.user_id %>
        <%= button_to("Delete", post_comment_path(@post.id, comment.id), method: :delete, class: 'btn btn-outline-primary delete-comment-button') %>
      <% end %> 
    <% end %>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Edit Your account</h1>
<%= link_to "Edit Password", user_edit_password_path(current_user) %>
<%= form_with model:@user do |form| %>
    <%= form.label :name, "Name" %>
    <br>
    <%= form.text_field :name %>
    <br>
    <%= form.label :email, "Email" %>
    <br>
    <%= form.text_field :email %>
    <br>
    <%= form.submit "Update Profile" %>
    <% end %>

app/views/users/edit_password.html.erb
<h1>Update Password</h1>

<%= form_with model:@user, url: user_update_password_path(current_user) do |form| %>
    <%= form.label :current_password, "Old Password" %>
    <br>
    <%= form.text_field :current_password, placeholder: "Old Password" %>
    <br>
    <%= form.label :new_password, "New Password" %>
    <br>
    <%= form.text_field :new_password %>
    <br>
    <%= form.label :new_password_confirmation, "Password Confirmation" %>
    <br>
    <%= form.text_field :new_password_confirmation %>
    <br>
    <%= form.submit "Update Password" %>
    <% end %>
    <% if flash.alert %>
  <% flash.each do |type, message| %>
      <%= type + " : " + message %>
    <% end %>
  <% end %>

app/views/users/new.html.erb
<h1>Sign Up Page</h1>

<%= form_with model:@user do |form| %>
    <%= form.label :name, "Name" %>
    <br>
    <%= form.text_field :name %>
    <br>
    <%= form.label :email, "Email" %>
    <br>
    <%= form.text_field :email %>
    <br>
    <%= form.label :password, "Password" %>
    <br>
    <%= form.text_field :password %>
    <br>
    <%= form.label :password_confirmation, "Password Confirmation" %>
    <br>
    <%= form.text_field :password_confirmation %>
    <br>
    <%= form.submit "Sign Up" %>
    <% if flash.notice %>
  <% flash.each do |type, message| %>
      <%= type + " : " + message %>
    <% end %>
  <% end %>
    <% end %>